Add `data-hashtags` for Facebook and Twitter
kytta/shareon pull request #60
Opened 2023-07-04 13:55 UTC by BeEdward

Hashtag and hastags are the most commonly used features on facebook and twitter respectively. Adding support to those two will make the library even more powerful.

This PR add two optional attribute `data-hashtag` for facebook and `data-hashtags` for twitter.

`data-hashtag` is a single key word without `#` while `data-hashtags` are comma seperated strings without `#`.

Closes #59

2023-07-06 09:46 UTC, kytta commented
Hi, sorry for having kept you waiting. Let me review this...

2023-07-06 09:54 UTC, kytta requested changes
Great job! Yet, I think two very similar properties will cause confusion. How about using just `hashtags` and then only taking the first one for Facebook? This, of course, will need to be reflected in the docs

2023-07-06 09:54 UTC, kytta commented on src/shareon.js
> +              ),
Let's delete this and only use `hashtags`

```suggestion
```

2023-07-06 09:54 UTC, kytta commented on src/shareon.js
> +                child.dataset.hashtags?.replaceAll(', ', ',') || container.dataset.hashtags?.replaceAll(', ', ',') || ""
Not a fan of this extra data validation. To keep the bundle size small, let's not fix the website owners' errors

```suggestion
                child.dataset.hashtags || container.dataset.hashtags || ""
```

2023-07-06 09:54 UTC, kytta commented on src/shareon.js
> +  facebook: (d) => `https://www.facebook.com/sharer/sharer.php?u=${d.url}${d.hashtag? `&hashtag=#${d.hashtag}` : ''}`,
Here, we'll take the first hashtag

```suggestion
  facebook: (d) => `https://www.facebook.com/sharer/sharer.php?u=${d.url}${d.hashtags? `&hashtag=#${d.hashtags.split(',')[0]}` : ''}`,
```

2023-07-06 12:45 UTC, BeEdward commented
> Great job! Yet, I think two very similar properties will cause confusion. How about using just `hashtags` and then only taking the first one for Facebook? This, of course, will need to be reflected in the docs

Sure. I can do that and will update shortly.

2023-07-07 20:53 UTC, kytta commented
Looks good! I hope I'll be able to merge it after some manual testing before Monday.

2023-07-07 20:53 UTC, kytta approved these changes

2023-07-10 10:20 UTC, kytta commented
Hey @BeEdward; can you elaborate on `hashtags` for the Facebook sharer? I have not found it in Facebook's documentation, and adding this parameter has no effect for me.

2023-07-11 13:57 UTC, BeEdward commented
> Hey @BeEdward; can you elaborate on `hashtags` for the Facebook sharer? I have not found it in Facebook's documentation, and adding this parameter has no effect for me.

I couldn't find the original documentation page, but in there old api, do you offer a `hashtag` parameter you can specify in the url. Here is a stackoverflow link I found
https://stackoverflow.com/questions/30806280/sharing-link-with-a-preset-hashtag

In their new dialogue api, they still have a `hashtag` parameter
https://developers.facebook.com/docs/sharing/reference/share-dialog

And in this repo https://ellisonleao.github.io/sharer.js/ , the author provide a `hashtag` option for facebook that totally work.

2023-07-11 14:21 UTC, kytta commented
> I couldn't find the original documentation page, but in there old api, do you offer a `hashtag` parameter you can specify in the url.
> In their new dialogue api, they still have a `hashtag` parameter 
> And in this repo , the author provide a `hashtag` option for facebook that totally work

Yup, thank you, I realized where the bug lies! The hash sign should be URL-encoded, or else it will parse as URL fragment

2023-07-11 14:22 UTC, kytta commented on src/shareon.js
> +  facebook: (d) => `https://www.facebook.com/sharer/sharer.php?u=${d.url}${d.hashtags? `&hashtag=#${d.hashtags.split(',')[0]}` : ''}`,
For everything to work, we need to escape two things:

- the hash sign
- the comma

```suggestion
  facebook: (d) => `https://www.facebook.com/sharer/sharer.php?u=${d.url}${d.hashtags? `&hashtag=%23${d.hashtags.split('%2C')[0]}` : ''}`,
```

2023-07-11 14:25 UTC, kytta requested changes
There are two things left: the URL encoding of some characters (see line comment) and documentation. Could you append the README [here](https://github.com/diffus-me/shareon/blob/73a7467cb48484ff25c0a4a544738f2bc235edd2/README.md?plain=1#L137-L143) with something like:

> add `data-hashtags` to a Twitter or Facebook button to include a hashtags. The value should be a comma-separated list of words. Facebook supports only one hashtag

2023-07-12 03:39 UTC, BeEdward commented
> There are two things left: the URL encoding of some characters (see line comment) and documentation. Could you append the README [here](https://github.com/diffus-me/shareon/blob/73a7467cb48484ff25c0a4a544738f2bc235edd2/README.md?plain=1#L137-L143) with something like:
> 
> > add `data-hashtags` to a Twitter or Facebook button to include a hashtags. The value should be a comma-separated list of words. Facebook supports only one hashtag

Sure. Will update momentarily.

2023-07-14 09:23 UTC, BeEdward commented
@kytta I think this is ready for commit

2023-07-14 20:13 UTC, merged

2023-07-14 22:47 UTC, kytta commented
Released in [v2.2.0](https://github.com/kytta/shareon/releases/tag/v2.2.0) 🎉