Added tumblr button
kytta/shareon pull request #80
Opened 2023-07-27 13:39 UTC by kabszac

Added tumblr button.
closes #76

2023-07-27 16:19 UTC, kytta commented on src/shareon.js
> + *   content?: string || [string]
Since the type of the post is always a link, this is also not needed, as we can use `url` instead

2023-07-27 16:20 UTC, kytta commented on src/shareon.js
> +  tumblr: (d) => `https://www.tumblr.com/widgets/share/tool?posttype=${d.posttype}&tags=${d.tags}${d.title? `&title=${d.title}`:''}&content=${d.content}${d.caption? `&caption=${d.caption}`:''}${d.via
Here and in other places: please, put Tumblr after Telegram to keep the alphabetical sorting.

2023-07-27 16:21 UTC, kytta commented on src/shareon.js
> +  tumblr: (d) => `https://www.tumblr.com/widgets/share/tool?posttype=${d.posttype}&tags=${d.tags}${d.title? `&title=${d.title}`:''}&content=${d.content}${d.caption? `&caption=${d.caption}`:''}${d.via
According to the comments above, rewrite this URL to only depend on `hashtags`, `title`, `url`, and `text` (which will become caption).

2023-07-28 21:33 UTC, kytta requested changes
Great, thanks! A couple of final touches from my side, and then I'll test and merge it

2023-07-28 21:33 UTC, kytta commented on src/shareon.js
> +  tumblr: (d) => `https://www.tumblr.com/widgets/share/tool?posttype=${d.url}&tags=${d.hashtags}${d.title? `&title=${d.title}`:''}&content=${d.content}${d.text? `&caption=${d.text}`:''}${d.via? `&sho
This still requires changes:

- `posttype` should be literally `link`
- `d.title` always exists, so we do not need to check it
- `d.tags` may or may not exist, so we need to check for this (see how Twitter button does it)
- `d.content` does not exist and should be `d.url` instead

```suggestion
  tumblr: (d) => `https://www.tumblr.com/widgets/share/tool?posttype=link${d.hashtags? `&tags=${d.hashtags}` : ''}&title=${d.title}&content=${d.url}${d.text? `&caption=${d.text}`:''}${d.via? `&show-via=${d.via}`:''}`,
```

2023-07-28 21:33 UTC, kytta commented on index.html
> +          <a class="tumblr"></a>
Please, put Tumblr between Telegram and Twitter to maintain alphabetical order everywhere where this applies (here, later in the HTML as well as in the CSS)

2023-07-28 21:33 UTC, kytta commented on src/shareon.js
> +  whatsapp: (d) => `https://wa.me/?text=${d.title}%0D%0A${d.url}${d.text ? `%0D%0A%0D%0A${d.text}` : ''}`
Please, bring the comma back :)

```suggestion
  whatsapp: (d) => `https://wa.me/?text=${d.title}%0D%0A${d.url}${d.text ? `%0D%0A%0D%0A${d.text}` : ''}`,
```

2023-07-31 13:47 UTC, kytta commented
Oh, thanks a lot for fixing the ordering of MS Teams, too! 😄 I'll test it and hopefully release a new version today

2023-07-31 13:56 UTC, kytta approved these changes

2023-07-31 21:08 UTC, merged

2023-07-31 21:08 UTC, kytta commented
Too late for me to release a new version; I hope it comes out tomorrow. Good night from my side, and thanks for the contribution!

2023-08-02 12:37 UTC, kabszac commented
welcome Kytta. Thank you for the guidance I hope to contribute more.